version: "3.5"
services:
  web:
    container_name: go-app
    build:
      dockerfile: Dockerfile
      context: .
    restart:
      always
    ports:
      - "${APP_PORT}:8000"
    environment:
      DD_DB_HOST: db
    depends_on:
      - db
    networks:
      - go_app
  db:
    container_name: go-db
    image: postgres:13-alpine
    restart:
      always
    ports:
      - '${PGPORT}:5432'
    environment:
      POSTGRES_USER: '${PGUSER}'
      POSTGRES_PASSWORD: '${PGPASSWORD}'
      POSTGRES_DB: '${PGDATABASE}'
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - go_app
networks:
  go_app:
    driver: bridge
volumes:
  dbdata:
    driver: local