http:
  port: 8000
  maxHeaderBytes: 10s
  readTimeout: 10s
  writeTimeout: 10s
db:
  username: "golang_user"
  host: "localhost"
  port: "5432"
  dbname: "weather"
  sslmode: "disable"
cache:
  ttl: 3600s