http:
  port: 8000
db:
  driver: "postgres"
  username: "golang_user"
  password: "golang_pass"
  host: "localhost"
  docker_host: "go-db"
  port: "5432"
  dbname: "weather"
  sslmode: "disable"
  url: "postgres://golang_user:golang_pass@localhost:5432/weather"
cache:
  ttl: 3600s